### ISSUE TITLE
[Refactor] Refactor Plan

### ISSUE THREAD

**Issue by sxzz** [element-plus/element-plus#6114]
## Plans

- remove all `@ts-nocheck`
- [`script-setup`](https://github.com/element-plus/element-plus/issues/5709)
   - refactor `state` to `ref`
   - expose all things user need
- [style namespace](https://github.com/element-plus/element-plus/issues/5374)
- [export component instance type](https://github.com/element-plus/element-plus/issues/4308)
- [refactor plan](https://github.com/element-plus/element-plus/pull/3113)
- [JSX](https://github.com/element-plus/element-plus/issues/5708)
   - Unit Test included
- Fix ALL TS errors, and add component path to `build/type-safe.json` and `build/type-safe-stricter.json`.

Please community contributors at me in your PR.

## Progress

- [x] affix
  - #6065
  - #6159
  - #6295
- [x] alert
  - #6066
  - #7973 
- [x] autocomplete
  - #6067
- [x] avatar
  - #6070
- [x] backtop
  - #6069
  - #6160
- [x] badge
  - #6068
  - #6247
- [x] breadcrumb / breadcrumb-item
  - #6073
- [x] button
  - #5933
- [x] button-group
  - #6256
- [x] calendar
  - #6682
- [x] card
  - #6071
- [x] carousel / carousel-item
  - #6681
- [ ] cascader / cascader-panel
- [x] check-tag
  - #6296
- [ ] checkbox / checkbox-button / checkbox-group
  - Assignee: @chenxch 
  - #7794 
- [x] col
  - #6303
  - assignee @HeftyKoo
- [x] collapse / collapse-item
  - #6307
- [x] collapse-transition
  - Assignee: @ryuhangyeong
  - #7953
- [x] collection
  - Assignee: @metanas
  - #7710
- [x] color-picker
  - #9672 
- [x] config-provider
  - Assignee: @holazz 
- [x] container / aside / footer / header / main
  - Assignee: @ryuhangyeong
  - #7725
  - #7707
- [ ] date-picker
  - Assignee: @JeremyWuuuuu 
- [ ] descriptions / descriptions-item
  - #8348
  - #8349
- [x] dialog
  - #6087
  - #6211
  - #6300
- [x] divider
  - #6556
- [ ] drawer [WIP]
  - assignee: @JeremyWuuuuu 
  - #6239
- [ ] dropdown / dropdown-item / dropdown-menu
- [x] empty
  - #6703
- [ ] focus-trap
- [x] form / form-item
  - assignees: @sxzz
  - #5401
- [x] icon
  - #5934
- [x] image
  - #6704 
- [x] image-viewer
  - #6704 
- [ ] infinite-scroll
- [x] input
  - #6545 
- [x] input-number
  - Assignee: @holazz
  - #7888
- [x] link
  - Assignee: @sxzz 
  - #6543
- [ ] loading
  - Assignee: @sxzz
- [ ] menu / menu-item / menu-item-group / sub-menu
- [ ] message
  - Assignee: @JeremyWuuuuu 
- [ ] message-box
  - Assignee: @JeremyWuuuuu 
- [ ] notification
  - Assignee: @JeremyWuuuuu 
- [ ] option / option-group
   - Assignee: @josonho
- [ ] overlay
  - Assignee: @ryuhangyeong
- [x] page-header
  - #6321
- [ ] pagination
  - Assignee: @metanas
  - #7730 
- [x] popconfirm
  - #7522
- [ ] popover
- [x] popper
  - #6725 
- [ ] progress
  - #7795
- [x] radio / radio-button / radio-group
  - #7701 
- [x] rate
  - #6565
- [x] result
  - Assignee: @ryuhangyeong
  - #7891
- [x] row
  - Assignee @HeftyKoo
  - #7961 
- [ ] roving-focus-group
- [x] row
  - #6354
- [x] scrollbar
  - Assignee: @holazz 
  - #7986
- [ ] select
- [ ] select-v2
- [x] skeleton / skeleton-item
  - #6395
- [x] slider
  - Assignee: @holazz 
  - #8008
- [x] slot
  - #6302
- [x] space
  - #8386 
- [x] step / steps
  - Assignee @ryuhangyeong
  - #7783
- [ ] switch
  - Assignee: @chenxch 
  - #7792  
- [ ] tabs / tab-pane
  - #6305
- [ ] ~~table / table-column~~
- [x] tag
  - #6288
- [x] teleport
  - #6301
- [ ] time-picker
- [ ] time-select
  - #7833
- [x] timeline / timeline-item
  - Assignee: @metanas
  - #7705 
- [x] tooltip
  - #9685 
- [ ] transfer
- [ ] tree
- [ ] tree-v2
- [x] upload
  - #6014
- [ ] virtual-list
- [ ] visual-hidden

**Comment by JeremyWuuuuu** [comment]
if anyone wants to help on this one you can simply ping me and tell me which component you intend to work on. 

template

```
Hi @JeremyWuuuuu, I'd like to work on [component name (Listed in the description)].

```

After I double checked there were no conflicts, you can begin working on that, I will include your name on the component above.

**Comment by josonho** [comment]
Hi @JeremyWuuuuu, I'd like to work on [option, option-group].

**Comment by JeremyWuuuuu** [comment]
@josonho Done!

**Comment by ryuhangyeong** [comment]
@JeremyWuuuuu hello. I want to contribute to Element Plus. I want to start with small components and refactor them to become more and more important. May I try refactoring the el-footer as a starting point?

**Comment by ryuhangyeong** [comment]
Hi @JeremyWuuuuu, I'd like to work on [el-footer, el-header, el-main, el-aside, el-container].

**Comment by JeremyWuuuuu** [comment]
@ryuhangyeong I would suggest we take 2 at a time, but since these 4 are under the same scope, I'll mark you as the owner. 

Thanks! :bow:

**Comment by chenxch** [comment]
Hi @JeremyWuuuuu , I'd like to work on [el-radio, el-radio-button, el-radio-group].

**Comment by chenxch** [comment]
Hi @JeremyWuuuuu , I'd like to work on [el-checkbox,el-checkbox-button,el-checkbox-group].

**Comment by ryuhangyeong** [comment]
Hi @JeremyWuuuuu, I'd like to work on [el-step, el-steps].

There are contributors who contributed to [el-header, el-footer, el-side] my previous assignments. So I write a reply to get an assignment for another component.

Thank you for your hard work.

**Comment by JeremyWuuuuu** [comment]
@chenxch @ryuhangyeong Hi guys, accepted. And updated! Thank you!

**Comment by Huangyuanx** [comment]
Hi @JeremyWuuuuu .I'd like to work on [message].  
But I made a pull request before ask you,can I continue?

**Comment by metanas** [comment]
Hi @JeremyWuuuuu, I was working on [Pagination] and his components [jumper, next, pager, prev, size, and total].

**Comment by JeremyWuuuuu** [comment]
> Hi @JeremyWuuuuu, I was working on [Pagination] and his components [jumper, next, pager, prev, size, and total].

Affirmative. You may proceed. 👍

**Comment by josonho** [comment]
Hi @JeremyWuuuuu .I'd like to work on [select]. While I'm dealing with option and option-group now, select is closely related to them

**Comment by chenxch** [comment]
Hi @JeremyWuuuuu , I'd like to work on [switch].

**Comment by metanas** [comment]
Hi @JeremyWuuuuu , I'd like to work on [time-select].

**Comment by holazz** [comment]
Hi @JeremyWuuuuu, I'd like to work on [input-number].

**Comment by JeremyWuuuuu** [comment]
> Hi @JeremyWuuuuu, I'd like to work on [input-number].

Got it. You may proceed. And before you begin coding, I would like to suggest that we can do this in multiple PRs which means we need to keep the PRs as small as possible. Thanks!

**Comment by holazz** [comment]
Hi @JeremyWuuuuu, I'd like to work on [config-provider].

**Comment by chenxch** [comment]
Hi @JeremyWuuuuu, I'd like to work on [link].

**Comment by logustra** [comment]
Hi @JeremyWuuuuu , I'd like to work on [link]

**Comment by ryuhangyeong** [comment]
Hi @JeremyWuuuuu , I'd like to work on [overlay]

**Comment by chenxch** [comment]
> Hi @JeremyWuuuuu , I'd like to work on [link]

`link` currently meets `script-setup` syntax, which can be ignored.

**Comment by btea** [comment]
> Hi @JeremyWuuuuu , I'd like to work on [link]  

This component has been refactored by #6543.

**Comment by chenxch** [comment]
> > Hi @JeremyWuuuuu , I'd like to work on [link]
> 
> This component has been refactored by #6543.


@logustra Are you interested in transforming unit tests into JSX?

**Comment by logustra** [comment]
> > > Hi @JeremyWuuuuu , I'd like to work on [link]
> > 
> > 
> > This component has been refactored by #6543.
> 
> @logustra Are you interested in transforming unit tests into JSX?

Sounds interesting, lemme do that then

**Comment by ryuhangyeong** [comment]
@chenxc Hello! Can I participate in that too?

**Comment by sxzz** [comment]
@ryuhangyeong Sure if you would like!

**Comment by chenxch** [comment]
> @chenxc Hello! Can I participate in that too?

Welcome.🤝

**Comment by holazz** [comment]
Hi @jw-foss , I'd like to work on [slider].

**Comment by jw-foss** [comment]
> Hi @jw-foss , I'd like to work on [slider].

Sure, off you go.

**Comment by holazz** [comment]
> Hi @JeremyWuuuuu, I'd like to work on [config-provider, scrollbar].

@jw-foss What about these two? I have created PRs before you replied to me, sorry 😅

**Comment by holazz** [comment]
Hi @jw-foss , I'd like to work on [popover].

**Comment by vecpeng** [comment]
Hi @JeremyWuuuuu, I'd like to work on [color-picker]

**Comment by LinZhanMing** [comment]
Hi @jw-foss , I'd like to work on [tooltip].

**Comment by sxzz** [comment]
I don't really need too many people to focus on  `JSX in Unit test` part, there are enough people @holazz @ryuhangyeong in this part at the moment.

**Comment by ryuhangyeong** [comment]
## Remaining part of `JSX in Unit test`

- 'cascader.test.ts'
- 'cascader-panel.test.ts'
- 'collection-item.test.ts'
- 'collection.test.ts'
- 'color-picker.test.ts'
- 'container.test.ts'
- 'date-picker.test.ts'
- 'date-time-picker.test.ts'
- 'descriptions.test.ts'
- 'dialog.test.ts'
- 'drawer.test.ts'
- 'dropdown.test.ts'
- 'focus-trap.test.ts'
- 'utils.test.ts'
- 'image-viewer.test.ts'
- 'infinite-scroll.test.ts'
- 'loading.test.ts'
- 'menu.test.ts'
- 'message.test.ts'
- 'message-box.test.ts'
- 'notification.test.ts'
- 'notify.test.ts'
- 'pagination.test.ts'
- 'directive.test.ts'
- 'popover.test.ts'
- 'arrow.test.ts'
- 'container.test.ts'
- 'content.test.ts'
- 'popper.test.ts'
- 'trigger.test.ts'
- 'roving-focus-group.test.ts'
- 'roving-focus-item.test.ts'
- 'util.test.ts'
- 'select.test.ts'
- 'select.test.ts'
- 'slider.test.ts'
- 'space.test.ts'
- 'steps.test.ts'
- 'switch.test.ts'
- 'table-column.test.ts'
- 'table.test.ts'
- 'tabs.test.ts'
- 'teleport.test.ts'
- 'time-picker.test.ts'
- 'time-select.test.ts'
- 'timeline.test.ts'
- 'content.test.ts'
- 'tooltip.test.ts'
- 'trigger.test.ts'
- 'transfer.test.ts'
- 'tree.test.ts'
- 'tree-select.test.ts'
- 'tree.test.ts'
- 'upload-dragger.test.ts'
- 'upload.test.ts'
- 'dynamic-size-grid.test.ts'
- 'dynamic-size-list.test.ts'
- 'fixed-size-grid.test.ts'
- 'fixed-size-list.test.ts'
- 'scrollbar.test.ts'

**Comment by webxmsj** [comment]
Hi , I'd like to work on [el-select].

**Comment by SnowingFox** [comment]
Hi @jw-foss , I'd like to work on [color-picker time-picker tooltip].

**Comment by SnowingFox** [comment]
Hi @jw-foss , I'd like to work on [tooltip transfer tree tree-v2].

**Comment by wiirhan** [comment]
Hi @jw-foss, I'd like to work on [cascader-panel].

**Comment by bing127** [comment]
日期选择器什么时候支持周、季度、年区间选择器了
